[package]
name = "translator"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
evalexpr = "12.0.2"
field_accessor = "0.5.2"
lookups = "0.2.0"
serde = { version = "1.0.217", features = ["derive"] }