[package]
name = "translator"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = { version = "1.5.5", features = ["derive"] }
mirror = { path = "./mirror" }
csv = "1.3.1"
evalexpr = "12.0.2"
lookups = "0.2.0"
regex = "1.11.1"
serde = { version = "1.0.217", features = ["derive"] }
